POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9wMTIzIiwiaWQiOiI2MjA1Mzc3ZGYyMTQ5N2Q1Y2I1ZDAwZGQiLCJpYXQiOjE2NDUwOTEzMDR9.jg3dEtI3fZ73froL7l4GRsuLvL9zqHlWfXBl_n2cmRs

{
    "title": "blog3",
    "author": "Dani",
    "url": "www.fi",
    "likes": 3
}